#!/bin/bash
APP_LABEL=app=node-k8s-app
NAMESPACE=default

SCRIPT_DIR=$(cd `dirname $0`; pwd)
SCRIPT=$SCRIPT_DIR/$(basename $0)
[[ -f $SCRIPT_DIR/.kubeconfig ]] && export KUBECONFIG=$SCRIPT_DIR/.kubeconfig
IMAGE_NAME=docker.io/yogendra/node-k8s-app:latest
DEMO_SESSION=probe-test

function first-pod {
  kubectl get pod -l app=node-k8s-app -o jsonpath="{.items[0].metadata.name}"
}
function second-pod {
  kubectl get pod -l app=node-k8s-app -o jsonpath="{.items[1].metadata.name}"
}

function demo-shell {
  tmux new-session -s $DEMO_SESSION \; \
    new-window \; \
    split-window -df "$SCRIPT api-watch $enpoint" \; \
    split-window -dht 2 "$SCRIPT logs-tail" \; \
    split-window -df "$SCRIPT assets-watch" \; \
    split-window -dht 4 "$SCRIPT events-watch" 
}

function assets-watch {
  FIRST_POD_NAME=$(first-pod)
  SECOND_POD_NAME=$(second-pod)
  while true ; do
    clear
    $SCRIPT assets-info $FIRST_POD_NAME $SECOND_POD_NAME
    sleep 2
  done
}

function assets-info {
  FIRST_POD_NAME=${1:-$(first-pod)}
  SECOND_POD_NAME=${2:-$(second-pod)}

  kubectl get -n $NAMESPACE pod,services -l $APP_LABEL -o wide
  echo "=== Application Endpoints in Service"
  kubectl describe -n $NAMESPACE  service -l $APP_LABEL  | grep Endpoint
  echo "=== $FIRST_POD_NAME - All Probe Flags ===" 
  kubectl exec $FIRST_POD_NAME -n $NAMESPACE -it -- curl -q localhost:3001/probes  | sed 's/true/"✅"/g;s/false/"❌"/g' | jq -c
  echo "=== $SECOND_POD_NAME - All Probe Flags ===" 
  kubectl exec $SECOND_POD_NAME -n $NAMESPACE -it -- curl -q localhost:3001/probes  | sed 's/true/"✅"/g;s/false/"❌"/g' | jq -c

}


function api-watch {
    
    LB=$(kubectl get service -n $NAMESPACE node-k8s-app -o jsonpath="{.status.loadBalancer.ingress[0].hostname}")
    URL=http://$LB/api/greeting
    
    if [[ -z $LB ]]; then
      echo forwarding localhost:3000 to service/node-k8s-app:80
      kubectl port-forward -n $NAMESPACE svc/node-k8s-app 3000:80 &> /dev/null &
      URL=http://localhost:3000/api/greeting
    fi
    echo LB=$LB,URL=$URL
    echo Watching $URL
    while true;
    do
      curl -q $URL
      echo
      sleep 0.5
    done
}
function pod-break {
  TYPE=${1?"Type not given"};shift
  POD_NAME=${1:-`first-pod`}
  kubectl exec $POD_NAME -n $NAMESPACE -it -- curl localhost:3001/probes/$TYPE/break 
}
function pod-fix {
  TYPE=${1?"Type not given"}; shift
  POD_NAME=${1:-`first-pod`}
  kubectl exec $POD_NAME -n $NAMESPACE -it -- curl localhost:3001/probes/$TYPE/fix
}

function logs-tail {
  kubectl logs -n $NAMESPACE -f -l $APP_LABEL --timestamps --prefix
}
function events-watch {
  kubectl get -n $NAMESPACE events -w
}


function image-build {
  docker build -t $IMAGE_NAME app
}
function image-publish {
  docker push $IMAGE_NAME
}
function image-publish-kind {
  kind load docker-image $IMAGE_NAME
}

function k8s-deploy {  
  kubectl apply -n $NAMESPACE -f k8s/node-k8s-app.yaml
}
function k8s-clean {
  kubectl delete -n $NAMESPACE -f k8s/node-k8s-app.yaml
}

command=${1:-demo-shell};shift
$command $*
