
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-k8s-app
  name: node-k8s-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-k8s-app
  template:
    metadata:
      labels:
        app: node-k8s-app
    spec:
      containers:
      - image: docker.io/yogendra/node-k8s-app:latest
        name: node-k8s-app
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 3001
          name: probe-port
        resources: 
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /probes/liveness
            port: probe-port
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 1
          failureThreshold: 1
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /probes/readiness
            port: probe-port
          initialDelaySeconds: 2
          periodSeconds: 5          
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
        startupProbe:
          httpGet:
            path: /probes/startup
            port: probe-port
          initialDelaySeconds: 2
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-k8s-app
  name: node-k8s-app
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: node-k8s-app
